name: bmi
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=h33c6efd_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0=pyh8b19718_0
  - python=3.12.12=hd63d673_2_cpython
  - readline=8.3=h853b02a_0
  - setuptools=80.10.2=pyh332efcf_0
  - tk=8.6.13=noxft_h366c992_103
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - arro3-core==0.6.5
      - arviz==0.23.1
      - arviz-stats==0.8.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - axial-positional-embedding==0.3.12
      - better-optimize==0.2.0
      - braindecode==1.3.2
      - cachetools==7.0.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cloudpickle==3.1.2
      - colt5-attention==0.11.1
      - cons==0.4.7
      - contourpy==1.3.3
      - coverage==7.13.3
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.3
      - cycler==0.12.1
      - decorator==5.2.1
      - docstring-inheritance==3.0.0
      - donfig==0.8.1.post1
      - dotenv==0.9.9
      - edfio==0.4.12
      - edflib-python==1.0.8
      - einops==0.8.2
      - etuples==0.3.10
      - executing==2.2.1
      - filelock==3.20.3
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - google-crc32c==1.8.0
      - h5netcdf==1.8.1
      - h5py==3.15.1
      - hyper-connections==0.4.7
      - idna==3.11
      - iniconfig==2.3.0
      - ipython==9.10.0
      - ipython-pygments-lexers==1.1.1
      - jax==0.9.0
      - jax-cuda12-pjrt==0.9.0
      - jax-cuda12-plugin==0.9.0
      - jaxlib==0.9.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - linear-attention-transformer==0.19.1
      - linformer==0.2.3
      - llvmlite==0.46.0
      - local-attention==1.11.2
      - logical-unification==0.4.7
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - minikanren==1.0.5
      - ml-dtypes==0.5.4
      - mne==1.11.0
      - mne-bids==0.18.0
      - moabb==1.4.3
      - mpmath==1.3.0
      - multidict==6.7.1
      - multipledispatch==1.0.0
      - networkx==3.6.1
      - numba==0.63.1
      - numcodecs==0.16.5
      - numpy==2.3.5
      - numpyro==0.20.0
      - nutpie==0.16.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.19.0.56
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.1.105
      - obstore==0.8.2
      - opt-einsum==3.4.0
      - pandas==3.0.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - pooch==1.9.0
      - preliz==0.23.0
      - product-key-memory==0.3.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==23.0.0
      - pycountry==24.6.1
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pymc==5.27.1
      - pymc-extras==0.7.0
      - pyparsing==3.3.2
      - pyriemann==0.10
      - pytensor==2.37.0
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.3.2
      - rotary-embedding-torch==0.8.9
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - seaborn==0.13.2
      - six==1.17.0
      - skorch==1.3.1
      - soundfile==0.13.1
      - stack-data==0.6.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - toolz==1.1.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchinfo==1.8.0
      - torchvision==0.20.1+cu121
      - tqdm==4.67.3
      - traitlets==5.14.3
      - triton==3.1.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - wcwidth==0.5.3
      - wfdb==4.3.1
      - xarray==2026.1.0
      - xarray-einstats==0.9.1
      - yarl==1.22.0
      - zarr==3.1.5
prefix: /data/davise5/miniconda3/envs/bmi
